### PR TITLE
chore(*): update react dependency

### PR DESCRIPTION
**Pull request by andresin87**
Become compatible with react 17 and 18

you can try it using [semver.npmjs.com](https://semver.npmjs.com/)

### CODE REVIEW

**Comment by garthenweb** [comment]
Thanks for the suggestion. I can confirm the library is working with react 17, but I didn't test it with react 18 so far.

Did you already try it? We might want to update the example and dev dependencies as well to cover the foundation at least before merging.

**Comment by andresin87** [comment]
I'll try later

**Comment by andresin87** [comment]
The most annoing part os react18 is the useEffect doble rendering in SSR but i this this library does not have any.

I'll rpepare an example with react 17 and 18 in https://codesandbox.io/

**Comment by andresin87** [comment]
✅ react 17: https://codesandbox.io/s/spring-pond-vwpf39
❌ react 18: https://codesandbox.io/s/busy-rain-xup66j

**Comment by andresin87** [comment]
I Updated finally to `"react": ">=16.3.0 <18.0.0"`
It works as you can see in the https://semver.npmjs.com
also in https://blog.greenkeeper.io/introduction-to-version-ranges-e0e8c6c85f0f

In @AdevintaSpain @sui-components  we are currently working using react17 so this update will be fine 4 us.

**Comment by andresin87** [comment]
🙏

**Comment by garthenweb** [comment]
Thanks. for the suggestion and for checking for react 18 as well. Took me some time to come back to this to double-check if it's safe to publish it.

**Pull request merged**
